#!/bin/csh -f
#

##  Copyright (C) 2017 Dennis J. Darland

##  This file is part of darland's philosophy.

##  darland's philosophy is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.

##  darland's philosophy is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.

##  You should have received a copy of the GNU General Public License
##  along with darland's philosophy.  If not, see <http://www.gnu.org/licenses/>

# Version of Wild-LIFE to use:
set MAPLE = "maple"

echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHere1"
    set maple_tests = 0
    set maple_tests_match = 0
    set maple_tests_differ = 0
    set maple_tests_out_differ = 0
    set maple_tests_err_differ = 0
# Run the philosophy suite
echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHere2"
foreach I ($*)
    @ maple_tests ++ 
echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHere3"

# make sure there are ref files
     touch REFOUT2/$I:r.refout
     touch REFERR2/$I:r.referr
echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHere4"

     if(-e IN2pre/$I:r.mxt) then
echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHere5"
     
# Run maple
#   (echo 'load("dummy.mxt")?' | tr -d ' ' ;echo "" ; \
#	cat IN2pre/$I:r.mxt  ; echo "halt?") | \
#	($MAPLE |  \
#egrep -v '(Loading|already loaded|Version|customizing|Cop#yright|Garbage|Exiting|X interface)' > OUT2/$I:r.out \
#        ) |& \
#        sed "s/.......s cpu (.*)//" > ERR2/$I:r.err
     
#     echo $MAPLE <IN2pre/$I:r.mxt > OUT2/$I:r.out 2>ERR2/$I:r.err
echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHere6"
     ($MAPLE <IN2pre/$I:r.mxt > OUT2/$I:r.out) |& \
      sed "s/hello//">ERR2/$I:r.err
echo "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHere7"
     
# Calculate the differences
    (diff OUT2/$I:r.out REFOUT2/$I:r.refout > REFDIFF2/$I:r.refdiff) >& /dev/null
    (diff ERR2/$I:r.err REFERR2/$I:r.referr > ERRDIFF2/$I:r.errdiff) >& /dev/null
    
# Report them to the developer
    if((`wc -c < REFDIFF2/$I:r.refdiff` != 0) || (`wc -c < ERRDIFF2/$I:r.errdiff` != 0)) then
    echo "./work2.sh $I:r"
    @ maple_tests_differ ++
    else
    echo "echo ./$I:r -- Matches Perfectly"
    @ maple_tests_match ++
    endif
    if (`wc -c < REFDIFF2/$I:r.refdiff` == 0) then
    rm -f REFDIFF2/$I:r.refdiff
    else
    @ maple_tests_out_differ ++
    endif
    if (`wc -c < ERRDIFF2/$I:r.errdiff` == 0) then
    rm -f ERRDIFF2/$I:r.errdiff
    else
	@ maple_tests_err_differ ++
	endif
	end
    echo "echo $maple_tests Total Tests completed"
    echo "echo $maple_tests_match Total Tests match"
    echo "echo $maple_tests_differ Total Tests differ"
    echo "echo $maple_tests_out_differ Total Tests out differ"
    echo "echo $maple_tests_err_differ Total Tests err differ"
	    endif
