#!/bin/csh -f
#

##  Copyright (C) 2017 Dennis J. Darland

##  This file is part of darland's philosophy.

##  darland's philosophy is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.

##  darland's philosophy is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.

##  You should have received a copy of the GNU General Public License
##  along with darland's philosophy.  If not, see <http://www.gnu.org/licenses/>

# Version of Wild-LIFE to use:
set WLIFE = "~/bin/wild_life_X"


    set life_tests = 0
    set life_tests_match = 0
    set life_tests_differ = 0
    set life_tests_out_differ = 0
    set life_tests_err_differ = 0
# Run the philosophy suite
foreach I ($*)
    @ life_tests ++ 

# make sure there are ref files
     touch REFOUT_UPDATED/$I:r.refout
     touch REFERR_UPDATED/$I:r.referr

     if(-e IN/$I:r.lf) then

# Run Wild-LIFE
   (echo 'load("dummy.lf")?' | tr -d ' ' ;echo "" ; \
	cat IN/$I:r.lf  ; echo "halt?") | \
	($WLIFE |  \
egrep -v '(Loading|already loaded|Version|customizing|Copyright|Garbage|Exiting|X interface)' > OUT/$I:r.out \
        ) |& \
        sed "s/.......s cpu (.*)//" > ERR/$I:r.err

# Calculate the differences
    (diff OUT/$I:r.out REFOUT_UPDATED/$I:r.refout > REFDIFF/$I:r.refdiff) >& /dev/null
    (diff ERR/$I:r.err REFERR_UPDATED/$I:r.referr > ERRDIFF/$I:r.errdiff) >& /dev/null
    
# Report them to the developer
    if((`wc -c < REFDIFF/$I:r.refdiff` != 0) || (`wc -c < ERRDIFF/$I:r.errdiff` != 0)) then
    echo "./work.sh $I:r"
    @ life_tests_differ ++
    else
    echo "echo ./$I:r -- Matches Perfectly"
    @ life_tests_match ++
    endif
    if (`wc -c < REFDIFF/$I:r.refdiff` == 0) then
    rm -f REFDIFF/$I:r.refdiff
    else
    @ life_tests_out_differ ++
    endif
    if (`wc -c < ERRDIFF/$I:r.errdiff` == 0) then
    rm -f ERRDIFF/$I:r.errdiff
    else
	@ life_tests_err_differ ++
	endif
	end
    echo "echo $life_tests Total Tests completed"
    echo "echo $life_tests_match Total Tests match"
    echo "echo $life_tests_differ Total Tests differ"
    echo "echo $life_tests_out_differ Total Tests out differ"
    echo "echo $life_tests_err_differ Total Tests err differ"
	    endif
