##  Copyright (C) 2017, 2021 Dennis J. Darland

##  This file is part of darland's philosophy.

##  darland's philosophy is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.

##  darland's philosophy is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.

##  You should have received a copy of the GNU General Public License
##  along with darland's philosophy.  If not, see <http://www.gnu.org/licenses/>.
echo "Darland Philosophy Individual Query Test Utility"
echo "enter 0 to proceed 999 to quit"
read select
while [ $select -ne 999 ]
do 
echo "-----------"
echo "Philosophy Input Files"
echo "-----------"
echo "NOTE: 31 forward are the current theory - still under development"
echo "31 Test darland_0031.lf Some examples understanding & number"
echo "32 Test darland_0032.lf Some examples belief & number"
echo "33 Test darland_0033.lf Idealism, Private Languages and Replacing Classes"
echo "34 Test darland_0034.lf Some examples opacity, agnosticism & number"
echo "35 Test darland_0035.lf Some examples multi test & number"
echo "36 Test darland_0036.lf Some examples agreement & number"
echo "37 Test darland_0037.lf Some examples essentially singular terms"
echo "38 Test darland_0038.lf Some examples plural terms"
echo "39 Test darland_0039.lf Some examples contingently singular terms"
echo "40 Test darland_0040.lf Some examples singular terms"
echo "41 Test darland_0041.lf Some examples for NAND Belief"
echo "42 Test darland_0042.lf Some examples for TRUE NAND Belief"
echo "45 Test darland_0045.lf Some examples Same Sense"
echo "46 Test darland_0046.lf Some examples Nonsense"
echo "47 Test darland_0047.lf Some examples Believing Nonsense"
echo "48 Test darland_0048.lf Some examples Natural Meaning Beliefs"
echo "61 Test darland_0061.lf Some examples PM Truth Functions"
echo "62 Test darland_0062.lf Some examples Satisfiability"
echo "63 Test darland_0063.lf Some examples Satisfiability with Statistics"
echo "64 Test darland_0064.lf Some examples Satisfiability Traversing Stats"
echo "65 Test darland_0065.lf Some examples Modified Satisfiability - 2"
echo "66 Test darland_0066.lf Some examples (100) Satisfiability 2 - generated tests"
echo "67 Test darland_0067.lf Some examples (100 worst case) Satisfiability 2 - generated tests"
echo "68 Test darland_0068.lf Corrected with Trace"
echo "69 Test darland_0069.lf Generated by Unicon Corrected with Trace"
echo "71 Test darland_0071.lf Some examples understanding in singular - WHITEHEAD PR"
echo "72 Test darland_0072.lf Some examples belief in singular - WHITEHEAD PR"
echo "73 Test darland_0073.lf FACTS Database check"
echo "74 Test darland_0074.lf Some examples opacity, agnosticism in singular - WHITEHEAD PR"
echo "75 Test darland_0075.lf Some examples essentially singular terms"
echo "76 Test darland_0076.lf Some examples plural terms"
echo "77 Test darland_0077.lf Some examples contingently singular terms"
echo "78 Test darland_0078.lf Some examples singular terms"
echo "-----------"
if test -f da_par_lf2.sh
then
echo "666 This File"
fi
echo "777 NOTES_DJD.txt"
echo "999 quit"
echo "select"
read select
case $select in
0) echo "Testing append"; cd ../DarlandPhilosophyWilder; ./work2.sh "append";;
1) echo "Testing 0001"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0001";;
2) echo "Testing 0002"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0002";;
3) echo "Testing 0003"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0003";;
4) echo "Testing 0004"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0004";;
5) echo "Testing 0005"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0005";;
6) echo "Testing 0006"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0006";;
7) echo "Testing 0007"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0007";;
8) echo "Testing 0008"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0008";;
9) echo "Testing 0009"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0009";;
10) echo "Testing 0010"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0010";;
21) echo "Testing 0021"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0021";;
22) echo "Testing 0022"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0022";;
23) echo "Testing 0023"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0023";;
24) echo "Testing 0024"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0024";;
25) echo "Testing 0025"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0025";;
26) echo "Testing 0026"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0026";;
27) echo "Testing 0027"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0027";;
28) echo "Testing 0028"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0028";;
31) echo "Testing 0031"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0031";;
32) echo "Testing 0032"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0032";;
33) echo "Testing 0033"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0033";;
34) echo "Testing 0034"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0034";;
35) echo "Testing 0035"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0035";;
36) echo "Testing 0036"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0036";;
37) echo "Testing 0037"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0037";;
38) echo "Testing 0038"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0038";;
39) echo "Testing 0039"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0039";;
40) echo "Testing 0040"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0040";;
41) echo "Testing 0041"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0041";;
42) echo "Testing 0042"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0042";;
45) echo "Testing 0045"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0045";;
46) echo "Testing 0046"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0046";;
47) echo "Testing 0047"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0047";;
48) echo "Testing 0048"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0048";;
61) echo "Testing 0061"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0061";;
62) echo "Testing 0062"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0062";;
63) echo "Testing 0063"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0063";;
64) echo "Testing 0064"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0064";;
65) echo "Testing 0065"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0065";;
66) echo "Testing 0066"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0066";;
67) echo "Testing 0067"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0067";;
68) echo "Testing 0068"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0068";;
69) echo "Testing 0069"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0069";;
71) echo "Testing 0071"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0071";;
72) echo "Testing 0072"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0072";;
73) echo "Testing 0073"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0073";;
74) echo "Testing 0074"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0074";;
75) echo "Testing 0075"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0075";;
76) echo "Testing 0076"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0076";;
77) echo "Testing 0077"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0077";;
78) echo "Testing 0078"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0078";;
56) echo "Testing 0000"; cd ../DarlandPhilosophyWilder; ./work2.sh "darland_0000";;
666) $EDITOR da_par_lf2.sh;;
777) $EDITOR NOTES_DJD.txt;;

esac
done

